name: phoenix_dash
description: Phoenix Dash - An exciting endless runner platformer game with stomp mechanics!
version: 2.0.0+1
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: '>=3.29.0'

dependencies:
  app_ui:
    path: packages/app_ui
  audioplayers: ^6.1.0
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.4
  cloud_firestore: ^5.6.3
  equatable: ^2.0.7
  file_selector: ^1.0.3
  firebase_analytics: ^11.4.3
  firebase_auth: ^5.5.2
  firebase_core: ^3.12.0
  flame: ^1.18.0
  flame_behaviors: ^1.0.0
  flame_tiled: ^1.20.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  leaderboard_repository:
    path: packages/leaderboard_repository
  leap: ^0.5.0
  logging: ^1.3.0
  ordered_set: ^6.0.1
  path: ^1.9.1
  pathxp: ^0.4.0
  provider: ^6.1.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^9.1.7
  flame_test: ^1.15.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

# These overrides are required for compatibility with the current Flutter version
dependency_overrides:
  flame_tiled:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: v1.18.0
      path: packages/flame_tiled
  leap:
    git:
      url: https://github.com/VeryGoodOpenSource/leap.git
      ref: vgv
      path: packages/leap

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/map/
    - assets/map/anim/
    - assets/map/tiles/
    - assets/map/objects/
    - assets/music/
    - assets/sfx/

flutter_launcher_icons:
  android: true
  adaptive_icon_foreround: "./android_icon.png"
  adaptive_icon_background: "#5ec7db"
  min_sdk_android: 26
  image_path: './android_icon.png'
  ios: 'ios_icon.png'
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'android_icon.png'
    background_color: '#0046a3'
    theme_color: '#5ec7db'
  windows:
    generate: true
    image_path: 'android_icon.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'android_icon.png'
