name: authentication_repository
description: Repository to manage authentication.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: '>=3.29.0'

dependencies:
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.12.0
  firebase_core_platform_interface: ^5.4.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
