name: leaderboard_repository
description: A repository to access leaderboard data in Firebase Cloud Firestore.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: '>=3.29.0'

dependencies:
  cloud_firestore: ^5.6.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
